"""add battle and battle histroy table

Revision ID: 10ab0d86f6ab
Revises: 3e67dd182bb0
Create Date: 2024-03-04 21:42:01.955459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ab0d86f6ab'
down_revision = '3e67dd182bb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('winner_id', sa.String(), nullable=True),
    sa.Column('loser_id', sa.String(), nullable=True),
    sa.Column('battle_started', sa.DateTime(), nullable=True),
    sa.Column('battle_ended', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loser_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battle_participants',
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('battle_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle_participants')
    op.drop_table('battle_history')
    op.drop_table('battle')
    # ### end Alembic commands ###
