"""Initial migration.

Revision ID: ff5aae98bb5e
Revises: 
Create Date: 2024-03-04 12:34:24.720215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5aae98bb5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move',
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('move_name', sa.String(length=50), nullable=False),
    sa.Column('move_type', sa.String(length=50), nullable=False),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('pp', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('effect', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('move_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pokemon',
    sa.Column('poke_id', sa.String(length=50), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('pokemon_name', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('shiny_image_url', sa.String(length=255), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('attack', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('special_attack', sa.Integer(), nullable=True),
    sa.Column('special_defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('abilities', sa.String(length=200), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('poke_id'),
    sa.UniqueConstraint('pokemon_id')
    )
    op.create_table('pokemon_moves',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['move.move_id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.pokemon_id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_moves')
    op.drop_table('pokemon')
    op.drop_table('user')
    op.drop_table('move')
    # ### end Alembic commands ###
